export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const UPDATE_SESSION = "UPDATE_SESSION";

export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const START_ML_SERVER = "START_ML_SERVER";
export const STOP_ML_SERVER = "STOP_ML_SERVER";
export const REQUEST_ML_SERVER_STATUS = "REQUEST_ML_SERVER_STATUS";
export const UPDATE_ML_SERVER_STATUS = "UPDATE_ML_SERVER_STATUS";

export const SEND_PROMPT = "SEND_PROMPT";

export const LOAD_IMAGES_REQUEST = "LOAD_IMAGES_REQUEST";
export const LOAD_IMAGES_SUCCESS = "LOAD_IMAGES_SUCCESS";

export const UPDATE_PROMPT= "UPDATE_PROMPT";
export const UPDATE_PRODUCT= "UPDATE_PRODUCT";
export const UPDATE_BANNER_FORMAT= "UPDATE_BANNER_FORMAT";
export const UPDATE_BANNER_TYPE= "UPDATE_BANNER_TYPE";
export const UPDATE_BANNER_WIDTH= "UPDATE_BANNER_WIDTH";
export const UPDATE_BANNER_HEIGHT= "UPDATE_BANNER_HEIGHT";
export const UPDATE_GENDER= "UPDATE_GENDER";
export const UPDATE_AGE= "UPDATE_AGE";
export const UPDATE_WAGE= "UPDATE_WAGE";
export const UPDATE_CLUSTER= "UPDATE_CLUSTER";